import moment from "moment";
import { codesplitsvg,forksvg,comment,stars, files } from "../svgs/svgs";



const Gist = ({ gist }) => 
<>  
    <div className="card">
        
            <div className="gist-header">
                <div className="title">
                    <img src={gist?.owner.avatar_url} />
                    <h3>{gist?.owner?.login || ''}</h3> 
                </div>
                <div className="icons">

                <span> <strong className="bg-blue" >{codesplitsvg} {Object.keys(gist.files)?.length} Files</strong>  </span>
                <span> <strong className="bg-blue" >{comment} Comments</strong> </span>
                <span> <strong className="bg-blue">{forksvg} Forks </strong></span>
                <span> <strong className="bg-blue"> {stars} Stars</strong> </span>
                </div>
            </div>
            <div className="createdUpdated">
                <span>Created At {moment(gist.created_at).format('ddd-mm-yy') }</span>
                <span>Last Updated {moment(gist.updated_at).format('ddd-mm-yy') }</span>
            </div>

            <div>
                Generated by 
            </div>
            <div className="fileIco">
                {Object.entries(gist.files)?.map((f)=>(<span> <strong className="bg-blue"> {files} {f[0]}</strong> </span>)) }
            </div>
    
    </div>
    
</>

export default Gist
